In [72]:
import pandas as pd
churn=pd.read_csv(r"C:\Users\rahma\Downloads\customer_churn_1M.csv")

In [73]:
churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 32 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   customer_id                  1000000 non-null  object
 1   signup_date                  1000000 non-null  object
 2   age                          1000000 non-null  int64
 3   gender                       1000000 non-null  object
 4   annual_income                970041 non-null   float64
 5   education                    1000000 non-null  object
 6   marital_status               1000000 non-null  object
 7   dependents                   1000000 non-null  int64
 8   tenure                       1000000 non-null  int64
 9   contract                     1000000 non-null  object
 10  payment_method               1000000 non-null  object
 11  paperless_billing            1000000 non-null  object
 12  senior_citizen               1000000 non-null  int64
 13  monthlycharges               1000000 non-null  float64
 14  totalcharges                 1000000 non-null  float64
 15  num_services                 1000000 non-null  int64
 16  has_phone_service            1000000 non-null  int64
 17  has_internet_service         1000000 non-null  int64
 18  has_online_security          1000000 non-null  int64
 19  has_online_backup            1000000 non-null  int64
 20  has_device_protection        1000000 non-null  int64
 21  has_tech_support             1000000 non-null  int64
 22  has_streaming_tv             1000000 non-null  int64
 23  has_streaming_movies         1000000 non-null  int64
 24  customer_satisfaction        980079 non-null   float64
 25  num_complaints               970094 non-null   float64
 26  num_service_calls            1000000 non-null  int64
 27  late_payments                1000000 non-null  int64
 28  avg_monthly_gb               949988 non-null   float64
 29  days_since_last_interaction  1000000 non-null  int64
 30  credit_score                 959605 non-null   float64
 31  churn                        1000000 non-null  int64
dtypes: float64(7), int64(17), object(8)
memory usage: 244.1+ MB

In [74]:
churn.shape

(1000000, 32)

In [75]:
churn.size

32000000

In [76]:
churn.head()

,customer_id,signup_date,age,gender,annual_income,education,marital_status,dependents,tenure,contract,...,has_streaming_tv,has_streaming_movies,customer_satisfaction,num_complaints,num_service_calls,late_payments,avg_monthly_gb,days_since_last_interaction,credit_score,churn
0,CUST0000000001,2022-12-12 12:53:58.199463,43,Female,55085.25,college,married,1,2,two_year,...,1,1,9.0,0.0,0,0,109.63,16,NaN,0
1,CUST0000000002,2022-01-13 12:53:58.199973,18,Male,60786.11,master,married,1,22,one_year,...,0,1,7.0,0.0,3,1,63.25,134,585.0,0
2,CUST0000000003,2023-09-04 12:53:58.199985,38,Female,73184.32,high_school,widowed,0,3,two_year,...,1,0,6.0,1.0,1,0,47.77,11,632.0,0
3,CUST0000000004,2022-06-27 12:53:58.199992,44,Male,40923.78,high_school,married,1,6,two_year,...,0,1,5.0,2.0,2,1,50.82,6,569.0,0
4,CUST0000000005,2022-12-08 12:53:58.199999,45,Female,36400.94,bachelor,single,0,9,two_year,...,0,1,8.0,1.0,1,0,16.74,18,657.0,0

In [77]:
churn.sample(10)

,customer_id,signup_date,age,gender,annual_income,education,marital_status,dependents,tenure,contract,...,has_streaming_tv,has_streaming_movies,customer_satisfaction,num_complaints,num_service_calls,late_payments,avg_monthly_gb,days_since_last_interaction,credit_score,churn
90179,CUST0000090180,2024-06-30 12:53:58.730175,31,Male,65486.67,bachelor,married,1,1,two_year,...,0,1,5.0,1.0,1,0,17.29,43,716.0,0
694681,CUST0000694682,2021-09-29 12:54:05.791744,32,Female,155929.91,master,married,1,40,one_year,...,1,1,7.0,1.0,2,0,0.00,112,635.0,0
648162,CUST0000648163,2025-03-01 12:54:05.523382,45,Female,149308.72,bachelor,single,1,7,two_year,...,1,0,9.0,4.0,3,0,4.22,8,529.0,0
976904,CUST0000976905,2023-06-04 12:54:09.351062,39,Female,105692.39,college,single,0,63,two_year,...,1,0,8.0,2.0,3,0,29.75,215,791.0,0
520601,CUST0000520602,2023-02-22 12:54:04.162861,55,Female,75258.26,bachelor,single,0,1,one_year,...,1,0,9.0,0.0,2,0,9.14,58,658.0,0
727763,CUST0000727764,2021-08-04 12:54:06.599671,50,Female,37279.35,college,single,1,55,two_year,...,1,0,3.0,3.0,3,1,82.60,182,682.0,0
788260,CUST0000788261,2023-04-14 12:54:06.940014,47,Female,66848.49,bachelor,single,0,52,one_year,...,1,1,5.0,0.0,1,0,9.29,33,679.0,0
849082,CUST0000849083,2024-07-18 12:54:07.944509,56,Male,34294.62,college,divorced,1,10,one_year,...,1,0,7.0,1.0,1,0,113.23,43,600.0,0
718365,CUST0000718366,2023-07-26 12:54:06.544942,47,Male,73840.55,high_school,single,0,1,one_year,...,0,1,6.0,0.0,2,1,38.69,52,747.0,0
913051,CUST0000913052,2023-10-28 12:54:08.984242,74,Male,28821.90,master,divorced,1,28,two_year,...,1,0,7.0,1.0,1,0,41.73,74,782.0,0

In [78]:
churn.describe()

,age,annual_income,dependents,tenure,senior_citizen,monthlycharges,totalcharges,num_services,has_phone_service,has_internet_service,...,has_streaming_tv,has_streaming_movies,customer_satisfaction,num_complaints,num_service_calls,late_payments,avg_monthly_gb,days_since_last_interaction,credit_score,churn
count,1000000.000000,970041.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,...,1000000.00000,1000000.000000,980079.000000,970094.000000,1000000.000000,1000000.000000,949988.000000,1000000.000000,959605.000000,1000000.000000
mean,44.724603,58788.311936,0.799831,22.381923,0.199511,86.443701,1837.321438,2.563721,0.769551,0.849742,...,0.59999,0.549086,6.159110,0.701667,1.760248,0.400969,39.095179,44.494191,678.562134,0.099227
std,14.479468,37137.433079,0.893654,20.073341,0.399633,27.592430,1803.721634,1.412330,0.421120,0.357324,...,0.48990,0.497585,2.328287,0.838148,1.485677,0.633289,43.852564,44.922587,87.642951,0.298967
min,18.000000,20000.000000,0.000000,1.000000,0.000000,20.000000,16.300000,1.000000,0.000000,0.000000,...,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,300.000000,0.000000
25%,34.000000,32712.560000,0.000000,6.000000,0.000000,70.490000,484.530000,1.000000,1.000000,1.000000,...,0.00000,0.000000,4.000000,0.000000,1.000000,0.000000,12.840000,12.000000,619.000000,0.000000
50%,44.000000,48954.600000,1.000000,16.000000,0.000000,85.480000,1249.750000,2.000000,1.000000,1.000000,...,1.00000,1.000000,7.000000,1.000000,1.000000,0.000000,27.770000,31.000000,680.000000,0.000000
75%,55.000000,73475.130000,1.000000,33.000000,0.000000,100.680000,2617.660000,3.000000,1.000000,1.000000,...,1.00000,1.000000,8.000000,1.000000,3.000000,1.000000,51.230000,62.000000,740.000000,0.000000
max,90.000000,250000.000000,5.000000,72.000000,1.000000,854.956730,16252.861508,6.000000,1.000000,1.000000,...,1.00000,1.000000,9.000000,7.000000,12.000000,5.000000,557.824023,365.000000,850.000000,1.000000

In [79]:
churn.isnull().sum()

customer_id                        0
signup_date                        0
age                                0
gender                             0
annual_income                  29959
education                          0
marital_status                     0
dependents                         0
tenure                             0
contract                           0
payment_method                     0
paperless_billing                  0
senior_citizen                     0
monthlycharges                     0
totalcharges                       0
num_services                       0
has_phone_service                  0
has_internet_service               0
has_online_security                0
has_online_backup                  0
has_device_protection              0
has_tech_support                   0
has_streaming_tv                   0
has_streaming_movies               0
customer_satisfaction          19921
num_complaints                 29906
num_service_calls                  0
late_payments                      0
avg_monthly_gb                 50012
days_since_last_interaction        0
credit_score                   40395
churn                              0
dtype: int64

In [80]:
churn.isnull().sum().sum()

170193

In [81]:
churn.duplicated().sum()

0

In [82]:
churn["customer_id"].duplicated().sum()

0

In [83]:
churn_rate=round(churn["churn"].mean() * 100,2)  
print(churn_rate)

9.92

In [84]:
for column in churn.columns:
    print(f"\n{column}:")
    print(churn[column].unique())

customer_id:
['CUST0000000001' 'CUST0000000002' 'CUST0000000003' ... 'CUST0000999998'
 'CUST0000999999' 'CUST0001000000']

signup_date:
['2022-12-12 12:53:58.199463' '2022-01-13 12:53:58.199973'
 '2023-09-04 12:53:58.199985' ... '2021-09-13 12:54:09.482423'
 '2025-08-30 12:54:09.482428' '2023-02-14 12:54:09.482434']

age:
[43 18 38 44 45 55 47 39 31 54 57 34 60 53 48 50 29 24 52 67 70 59 25 42
 49 33 63 30 35 20 71 37 41 64 40 46 56 51 66 62 68 58 22 23 28 72 36 21
 32 65 61 84 27 82 74 75 90 76 26 69 73 19 78 81 87 85 89 83 77 80 79 86
 88]

gender:
['Female' 'Male' 'Other']

annual_income:
[ 55085.25  60786.11  73184.32 ... 164236.89  34258.27  23617.51]

education:
['college' 'master' 'high_school' 'bachelor' 'phd']

marital_status:
['married' 'widowed' 'single' 'divorced']

dependents:
[1 0 2 3 4 5]

tenure:
[ 2 22  3  6  9 47 26 18  1 31 12 38  7 48  5 44 45 72 11 14 54  8 15 24
 57 17  4 23 19 29 25 21 33 30 28 69 16 55 20 51 32 13 52 68 36 56 61 42
 40 43 10 65 60 27 50 41 35 37 53 39 63 34 58 59 64 71 62 49 70 66 46 67]

contract:
['two_year' 'one_year' 'month_to_month']

payment_method:
['electronic_check' 'bank_transfer' 'credit_card' 'mailed_check']

paperless_billing:
['Yes' 'No']

senior_citizen:
[0 1]

monthlycharges:
[ 67.2         71.54       112.2        ... 164.25       178.17
 403.30550439]

totalcharges:
[ 144.39       1602.22        328.81       ...  824.9039281  3138.37427663
 2901.11      ]

num_services:
[1 2 4 3 6 5]

has_phone_service:
[1 0]

has_internet_service:
[1 0]

has_online_security:
[0 1]

has_online_backup:
[0 1]

has_device_protection:
[1 0]

has_tech_support:
[1 0]

has_streaming_tv:
[1 0]

has_streaming_movies:
[1 0]

customer_satisfaction:
[ 9.  7.  6.  5.  8.  4.  2.  3.  1. nan]

num_complaints:
[ 0.  1.  2. nan  3.  4.  5.  6.  7.]

num_service_calls:
[ 0  3  1  2  4  6  5  9  7  8 10 12 11]

late_payments:
[0 1 2 3 4 5]

avg_monthly_gb:
[109.63  63.25  47.77 ... 387.59 264.6  266.11]

days_since_last_interaction:
[ 16 134  11   6  18  22 106  28  91 123   1  26  33  83  70 139  19  14
  50   4  12  78 141 264   3  41   2  52  35   7   5  58  59   8  21  75
  43  61  17 149  46  13 129  57 202 102  23 185  79  15  60  74  76  29
  47  31  71  63  92  30 110  25  93  87  51 167  36  68 205  72  42 101
  38  55  10  62   9 126  44  24 138  48  95  66 172  39 274 143  56  54
 150  94 195 118  99  40 184 120 227 180  81  49  77  32  37  80 124  34
  64 105 216 176  82 164 114 144 186  86  98  27 147 135 116  53 107 122
 108 100 226  84  88 192 232 131 276 142 133  20 182 221  67 130 187  69
 115 148 145 262 113 121 174 171  73  96  45 103 112 117 154 181 163 119
 159 137  90 170  85 197 168 250 218 156 278 153 191 127 220 173 177 175
 151  89 231 109 158 223  97 200 128 233 155 211 104 365 136 132  65 255
 190 247 307 162 198 194 272 201 166 189 125 266 270 263 111 169 193 243
 178 165 252 208 196 140 210 146 230 342 284 215 248 213 161 207 341 157
 152 259 241 350 329 224 212 305 257 183 246 271 344 242 267 206 160 285
 249 204 288 209 260 228 217 289 265 199 179 203 244 308 235 237 253 214
 188 236 352 312 273 337 225 339 219 323 354 254 238 251 304 335 306 301
 258 299 269 239 316 286 326 297 234 327 222 332 268 296 245 229 293 256
 287 294 277 313 318 351 319 275 291 317 282 311 300 302 310 261 240 279
 336 309 280 322 325 290 345 334 298 303 315 358 330 320 353 283 292 314
 328 340 321 338 360 364 281 295 357 348 346 356 343 359 361 349 347 331
 324 355 362 363 333]

credit_score:
[ nan 585. 632. 569. 657. 702. 716. 525. 637. 850. 535. 681. 655. 698.
 572. 731. 682. 654. 772. 749. 816. 656. 699. 636. 627. 652. 553. 735.
 748. 631. 720. 719. 723. 705. 695. 747. 612. 555. 614. 804. 628. 732.
 606. 689. 767. 803. 609. 769. 770. 822. 621. 807. 676. 640. 756. 771.
 662. 697. 615. 625. 544. 647. 668. 684. 759. 805. 626. 508. 429. 688.
 505. 610. 691. 550. 607. 666. 709. 635. 589. 712. 728. 554. 646. 777.
 651. 808. 601. 754. 744. 524. 560. 800. 714. 645. 672. 778. 659. 745.
 567. 547. 620. 733. 741. 633. 704. 523. 734. 478. 758. 787. 545. 618.
 624. 692. 608. 649. 760. 707. 765. 690. 730. 752. 642. 475. 677. 653.
 541. 596. 726. 711. 643. 587. 675. 484. 472. 727. 588. 761. 658. 703.
 683. 746. 419. 590. 410. 708. 687. 788. 611. 543. 680. 718. 634. 742.
 710. 724. 616. 802. 774. 613. 798. 843. 603. 551. 568. 725. 737. 597.
 638. 605. 599. 557. 715. 561. 739. 575. 639. 507. 721. 743. 738. 663.
 791. 617. 538. 775. 782. 844. 577. 740. 847. 619. 528. 685. 495. 780.
 763. 678. 552. 534. 549. 520. 764. 573. 462. 783. 669. 781. 598. 602.
 670. 600. 578. 570. 661. 693. 574. 532. 679. 696. 755. 592. 722. 641.
 629. 818. 701. 473. 673. 486. 813. 768. 405. 563. 519. 751. 827. 630.
 686. 531. 801. 571. 706. 517. 736. 826. 667. 700. 829. 664. 717. 622.
 500. 559. 660. 509. 583. 784. 584. 750. 503. 814. 674. 434. 623. 488.
 516. 644. 464. 812. 671. 776. 665. 713. 502. 540. 828. 466. 496. 591.
 810. 836. 565. 579. 521. 773. 757. 820. 650. 533. 581. 779. 482. 834.
 409. 832. 512. 819. 785. 837. 792. 830. 694. 729. 562. 815. 582. 558.
 593. 467. 823. 527. 556. 848. 809. 498. 838. 796. 378. 821. 839. 580.
 576. 504. 799. 452. 762. 604. 786. 648. 542. 793. 489. 849. 789. 846.
 811. 483. 454. 586. 548. 594. 753. 499. 425. 435. 529. 518. 817. 526.
 831. 476. 795. 469. 515. 451. 835. 766. 470. 406. 380. 595. 514. 481.
 438. 842. 440. 794. 536. 387. 546. 492. 477. 510. 564. 511. 539. 493.
 490. 566. 463. 790. 841. 797. 471. 397. 506. 825. 833. 418. 530. 446.
 522. 399. 479. 480. 485. 468. 491. 806. 537. 474. 824. 443. 449. 300.
 840. 424. 497. 494. 371. 358. 386. 513. 413. 401. 420. 448. 458. 461.
 423. 445. 447. 402. 487. 444. 845. 407. 453. 456. 501. 377. 396. 428.
 427. 455. 457. 430. 338. 416. 388. 433. 415. 442. 432. 404. 403. 439.
 421. 411. 437. 436. 450. 365. 460. 412. 390. 417. 376. 400. 459. 408.
 393. 422. 414. 441. 426. 329. 328. 382. 465. 431. 398. 309. 383. 394.
 375. 344. 391. 374. 389. 381. 357. 392. 342. 385. 372. 317. 384. 364.
 318. 311. 362. 353. 368. 323. 366. 347. 395. 373. 324. 343. 345. 359.
 355. 363. 350. 356. 340. 370. 348. 354. 361. 367. 337. 360. 341. 349.
 339. 325. 321. 351. 327. 369. 322. 352. 304. 314. 336. 379. 307. 332.
 331. 326. 306. 308. 319. 346. 312. 320.]

churn:
[0 1]

# 2-Feature selection

In [86]:
columns_to_drop = ['gender','education','marital_status','senior_citizen','paperless_billing','avg_monthly_gb','credit_score','signup_date',
'has_device_protection' ,'has_streaming_tv','has_streaming_movies','has_phone_service' ,'has_online_backup']

churn= churn.drop(columns=columns_to_drop)

In [87]:
churn.shape

(1000000, 19)

# 3-Data cleaning

# Handle missing values

In [90]:
null_percentage= (churn.isnull().mean() * 100).round(1)
print(null_percentage)

customer_id                    0.0
age                            0.0
annual_income                  3.0
dependents                     0.0
tenure                         0.0
contract                       0.0
payment_method                 0.0
monthlycharges                 0.0
totalcharges                   0.0
num_services                   0.0
has_internet_service           0.0
has_online_security            0.0
has_tech_support               0.0
customer_satisfaction          2.0
num_complaints                 3.0
num_service_calls              0.0
late_payments                  0.0
days_since_last_interaction    0.0
churn                          0.0
dtype: float64

In [91]:
def check_outliers(column):   
    Q1= column.quantile(0.25)
    Q3= column.quantile(0.75)
    
    IQR= Q3 - Q1
    
    lower_bound= Q1 - 1.5 * IQR
    upper_bound= Q3 + 1.5 * IQR
    
    outliers= column[(column < lower_bound) | (column > upper_bound)]
    
    if len(outliers)>0:
        print("There are outliers in ",column.name)
    else:
        print("There are no outliers in ",column.name)

check_outliers(churn["annual_income"])
check_outliers(churn["customer_satisfaction"])
check_outliers(churn["num_complaints"])

There are outliers in  annual_income
There are no outliers in  customer_satisfaction
There are outliers in  num_complaints

In [92]:
churn['annual_income'] = churn['annual_income'].fillna(churn['annual_income'].median())

In [93]:
churn['customer_satisfaction'] = churn['customer_satisfaction'].fillna(churn['customer_satisfaction'].mean())

In [94]:
churn['num_complaints'] = churn['num_complaints'].fillna(churn['num_complaints'].median())

In [95]:
churn.isnull().sum()

customer_id                    0
age                            0
annual_income                  0
dependents                     0
tenure                         0
contract                       0
payment_method                 0
monthlycharges                 0
totalcharges                   0
num_services                   0
has_internet_service           0
has_online_security            0
has_tech_support               0
customer_satisfaction          0
num_complaints                 0
num_service_calls              0
late_payments                  0
days_since_last_interaction    0
churn                          0
dtype: int64

In [96]:
cols = ["has_internet_service","has_online_security","has_tech_support","churn"]
churn[cols] = churn[cols].replace({0: 'No', 1: 'Yes'})

In [97]:
churn["churn"].unique()

array(['No', 'Yes'], dtype=object)

# change dtypes

In [99]:
churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 19 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   customer_id                  1000000 non-null  object
 1   age                          1000000 non-null  int64
 2   annual_income                1000000 non-null  float64
 3   dependents                   1000000 non-null  int64
 4   tenure                       1000000 non-null  int64
 5   contract                     1000000 non-null  object
 6   payment_method               1000000 non-null  object
 7   monthlycharges               1000000 non-null  float64
 8   totalcharges                 1000000 non-null  float64
 9   num_services                 1000000 non-null  int64
 10  has_internet_service         1000000 non-null  object
 11  has_online_security          1000000 non-null  object
 12  has_tech_support             1000000 non-null  object
 13  customer_satisfaction        1000000 non-null  float64
 14  num_complaints               1000000 non-null  float64
 15  num_service_calls            1000000 non-null  int64
 16  late_payments                1000000 non-null  int64
 17  days_since_last_interaction  1000000 non-null  int64
 18  churn                        1000000 non-null  object
dtypes: float64(5), int64(7), object(7)
memory usage: 145.0+ MB

In [100]:
churn['customer_id'] =churn['customer_id'].astype('string')
churn['age'] = churn['age'].astype(int)
churn['contract'] = churn['contract'].astype('string')
churn['payment_method'] = churn['payment_method'].astype('string')
churn['has_internet_service'] = churn['has_internet_service'].astype('string')
churn['has_tech_support'] = churn['has_tech_support'].astype('string')
churn['has_online_security'] = churn['has_online_security'].astype('string')
churn['has_online_security'] = churn['has_online_security'].astype('string')
churn['churn'] = churn['churn'].astype('string')
churn['customer_satisfaction'] = churn['customer_satisfaction'].astype(int)
churn['num_complaints'] = churn['num_complaints'].astype(int)
churn['annual_income'] = churn['annual_income'].astype(float)
churn['monthlycharges'] = churn['monthlycharges'].astype(float)
churn['totalcharges'] = churn['totalcharges'].astype(float)

In [101]:
churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 19 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   customer_id                  1000000 non-null  string
 1   age                          1000000 non-null  int32
 2   annual_income                1000000 non-null  float64
 3   dependents                   1000000 non-null  int64
 4   tenure                       1000000 non-null  int64
 5   contract                     1000000 non-null  string
 6   payment_method               1000000 non-null  string
 7   monthlycharges               1000000 non-null  float64
 8   totalcharges                 1000000 non-null  float64
 9   num_services                 1000000 non-null  int64
 10  has_internet_service         1000000 non-null  string
 11  has_online_security          1000000 non-null  string
 12  has_tech_support             1000000 non-null  string
 13  customer_satisfaction        1000000 non-null  int32
 14  num_complaints               1000000 non-null  int32
 15  num_service_calls            1000000 non-null  int64
 16  late_payments                1000000 non-null  int64
 17  days_since_last_interaction  1000000 non-null  int64
 18  churn                        1000000 non-null  string
dtypes: float64(3), int32(3), int64(6), string(7)
memory usage: 133.5 MB

# organizing data

In [103]:
churn=churn.rename(columns={'tenure': 'tenure(months)'})

In [104]:
churn['has_internet_service'] = churn['has_internet_service'].str.upper()
churn['has_online_security'] = churn['has_online_security'].str.upper()
churn['has_tech_support'] = churn['has_tech_support'].str.upper()
churn['churn'] = churn['churn'].str.upper()
churn['payment_method'] = churn['payment_method'].str.upper()
churn['contract'] = churn['contract'].str.upper()

In [105]:
churn.head()

,customer_id,age,annual_income,dependents,tenure(months),contract,payment_method,monthlycharges,totalcharges,num_services,has_internet_service,has_online_security,has_tech_support,customer_satisfaction,num_complaints,num_service_calls,late_payments,days_since_last_interaction,churn
0,CUST0000000001,43,55085.25,1,2,TWO_YEAR,ELECTRONIC_CHECK,67.20,144.39,1,YES,NO,YES,9,0,0,0,16,NO
1,CUST0000000002,18,60786.11,1,22,ONE_YEAR,BANK_TRANSFER,71.54,1602.22,2,YES,NO,NO,7,0,3,1,134,NO
2,CUST0000000003,38,73184.32,0,3,TWO_YEAR,CREDIT_CARD,112.20,328.81,4,YES,NO,YES,6,1,1,0,11,NO
3,CUST0000000004,44,40923.78,1,6,TWO_YEAR,BANK_TRANSFER,107.49,643.45,3,YES,NO,YES,5,2,2,1,6,NO
4,CUST0000000005,45,36400.94,0,9,TWO_YEAR,CREDIT_CARD,110.05,648.79,3,YES,NO,NO,8,1,1,0,18,NO

In [106]:
churn['payment_method'] = churn['payment_method'].str.replace('_',' ')
churn['contract'] = churn['contract'].str.replace('_',' ')

In [107]:
churn.sample(10)

,customer_id,age,annual_income,dependents,tenure(months),contract,payment_method,monthlycharges,totalcharges,num_services,has_internet_service,has_online_security,has_tech_support,customer_satisfaction,num_complaints,num_service_calls,late_payments,days_since_last_interaction,churn
80408,CUST0000080409,50,42318.24,0,41,ONE YEAR,CREDIT CARD,91.93,3619.07,2,YES,YES,YES,8,0,0,1,38,NO
505470,CUST0000505471,46,181133.30,1,62,TWO YEAR,ELECTRONIC CHECK,73.67,4368.56,3,YES,YES,NO,6,1,4,0,49,NO
104957,CUST0000104958,56,38534.47,1,6,TWO YEAR,ELECTRONIC CHECK,64.73,360.15,1,YES,NO,NO,4,0,0,0,153,NO
736105,CUST0000736106,35,31303.45,1,72,TWO YEAR,CREDIT CARD,102.18,7477.66,2,YES,NO,YES,9,0,2,0,9,NO
9912,CUST0000009913,28,27178.63,0,24,TWO YEAR,CREDIT CARD,101.93,1872.83,3,YES,YES,YES,6,0,1,1,22,NO
805307,CUST0000805308,73,23748.93,1,5,ONE YEAR,BANK TRANSFER,92.55,492.89,4,YES,NO,YES,5,1,1,1,9,NO
537461,CUST0000537462,59,60150.37,0,11,ONE YEAR,ELECTRONIC CHECK,120.68,1277.01,4,YES,NO,YES,4,0,1,1,46,YES
65441,CUST0000065442,37,56814.25,1,26,ONE YEAR,CREDIT CARD,117.39,3185.40,3,YES,YES,YES,2,0,1,0,36,NO
485214,CUST0000485215,60,60793.05,1,14,TWO YEAR,BANK TRANSFER,76.08,1162.38,4,YES,YES,NO,4,0,1,2,67,NO
314822,CUST0000314823,34,24481.83,0,2,ONE YEAR,BANK TRANSFER,90.38,190.00,2,YES,YES,NO,8,1,1,1,99,NO

# Handle inconsistent values

In [109]:
(churn['totalcharges'] < churn['monthlycharges']).sum()

45840

In [110]:
churn[churn['totalcharges'] < churn['monthlycharges']]['tenure(months)'].value_counts()

tenure(months)
1     45652
2        50
3        37
4        25
5        20
6        13
10       10
9         8
7         8
8         7
13        3
11        2
15        2
14        1
29        1
12        1
Name: count, dtype: int64

In [111]:
(churn['tenure(months)'] == 1).sum()

79625

In [112]:
churn.loc[churn['tenure(months)'] == 1, 'totalcharges'] = churn.loc[
    churn['tenure(months)'] == 1, 'monthlycharges'
]

In [113]:
(churn['totalcharges'] < churn['monthlycharges']).sum()

188

In [114]:
churn.loc[churn['totalcharges'] < churn['monthlycharges']]

,customer_id,age,annual_income,dependents,tenure(months),contract,payment_method,monthlycharges,totalcharges,num_services,has_internet_service,has_online_security,has_tech_support,customer_satisfaction,num_complaints,num_service_calls,late_payments,days_since_last_interaction,churn
9350,CUST0000009351,45,51612.30,0,5,ONE YEAR,CREDIT CARD,853.190579,448.670000,3,YES,NO,YES,5,0,1,0,51,NO
13828,CUST0000013829,62,94823.94,0,3,ONE YEAR,ELECTRONIC CHECK,679.421272,378.400000,3,YES,YES,YES,9,0,2,0,53,NO
29895,CUST0000029896,57,48335.78,0,2,TWO YEAR,MAILED CHECK,54.470000,46.174488,2,NO,NO,NO,6,0,1,0,67,NO
33789,CUST0000033790,28,189892.64,1,5,ONE YEAR,CREDIT CARD,746.697609,487.800000,4,YES,NO,YES,3,2,4,0,11,NO
36799,CUST0000036800,29,20000.00,1,3,ONE YEAR,CREDIT CARD,674.289200,129.980000,1,NO,NO,NO,8,1,1,0,8,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985622,CUST0000985623,67,96757.43,0,2,ONE YEAR,CREDIT CARD,53.670000,52.503507,1,NO,NO,NO,1,2,2,0,7,YES
988843,CUST0000988844,53,49790.27,0,2,ONE YEAR,ELECTRONIC CHECK,553.444827,155.240000,1,YES,YES,YES,5,1,1,2,1,NO
993022,CUST0000993023,73,56342.55,1,2,ONE YEAR,ELECTRONIC CHECK,82.120000,56.094567,1,YES,NO,YES,7,0,1,1,69,NO
994595,CUST0000994596,44,60848.11,2,12,TWO YEAR,CREDIT CARD,823.808563,745.260000,3,YES,NO,NO,5,2,0,1,33,NO
995330,CUST0000995331,46,48954.60,1,4,ONE YEAR,ELECTRONIC CHECK,374.623858,331.260000,3,YES,NO,NO,6,1,0,1,1,NO

In [115]:
churn = churn.drop(churn[churn['totalcharges'] < churn['monthlycharges']].index)

In [116]:
(churn['totalcharges'] < churn['monthlycharges']).sum()

0

In [117]:
churn.to_csv("Final_Projectt.csv")

# Feature Enginnering

In [119]:
churn.columns

Index(['customer_id', 'age', 'annual_income', 'dependents', 'tenure(months)',
       'contract', 'payment_method', 'monthlycharges', 'totalcharges',
       'num_services', 'has_internet_service', 'has_online_security',
       'has_tech_support', 'customer_satisfaction', 'num_complaints',
       'num_service_calls', 'late_payments', 'days_since_last_interaction',
       'churn'],
      dtype='object')

In [120]:
churn["Charges_Per_Service"] = churn["monthlycharges"] / churn["num_services"].replace(0, 1)

In [121]:
churn["Charges_Per_Tenure_Month"] = churn["totalcharges"] / churn["tenure(months)"].replace(0, 1)

In [122]:
churn["ServiceCalls_Per_Service"] = churn["num_service_calls"] / churn["num_services"].replace(0, 1)

In [123]:
churn["Age_Group"] = pd.cut(churn["age"],
    bins=[0, 18, 30, 45, 60, 100],
    labels=["Under 18", "Young", "Adult", "Middle Age", "Senior"],)

In [124]:
churn["Service_Efficiency"] = churn["num_services"] / churn["tenure(months)"].replace(0, 1)

In [125]:
churn["Satisfaction_Category"] = pd.cut(churn["customer_satisfaction"],
    bins=[-1, 3, 5, 7, 10],
    labels=["Poor", "Average", "Good", "Excellent"],)

In [126]:
churn["Complaints_Calls_Gap"] = churn["num_complaints"] - churn["num_service_calls"]

In [127]:
churn["Calls_Per_Tenure_Month"] = churn["num_service_calls"] / churn["tenure(months)"].replace(0, 1)

In [128]:
churn["Is_Long_Tenure"] = (churn["tenure(months)"] > churn["tenure(months)"].quantile(0.75)).astype(int)

In [129]:
churn["MonthlyCharges_Category"] = pd.cut(churn["monthlycharges"],
    bins=[0, 35, 70, 120, churn["monthlycharges"].max()],
    labels=["Low", "Medium", "High", "Very High"],)

In [130]:
churn["Avg_MonthlyCharges_By_Contract"] = churn.groupby("contract")["monthlycharges"].transform("mean")

In [131]:
churn["Risk_Score"] = (
    (churn["late_payments"] > 0).astype(int) * 30 +
    (churn["customer_satisfaction"] <= 2).astype(int) * 25 +
    (churn["contract"] == 'Month-to-Month').astype(int) * 25 +
    (churn["num_complaints"] > 2).astype(int) * 20
)

In [132]:
churn["Risk_Level"] = pd.cut(
    churn["Risk_Score"],
    bins=[-1, 25, 55, 100],
    labels=["Low Risk", "Medium Risk", "High Risk"]
)

In [133]:
churn[["Risk_Score", "Risk_Level"]].head()

   Risk_Score   Risk_Level
0           0     Low Risk
1          30  Medium Risk
2           0     Low Risk
3          30  Medium Risk
4           0     Low Risk

In [134]:
churn["Risk_Level"].value_counts()

Risk_Level
Low Risk       667747
Medium Risk    331083
High Risk         982
Name: count, dtype: int64

In [135]:
RFM = pd.DataFrame({
    'customer_id': churn['customer_id'],
    'R_Recency': churn['days_since_last_interaction'],
    'F_frequency': churn['num_services'],
    'M_Monetary': churn['totalcharges']
})

RFM

           customer_id  R_Recency  F_frequency  M_Monetary
0       CUST0000000001         16            1      144.39
1       CUST0000000002        134            2     1602.22
2       CUST0000000003         11            4      328.81
3       CUST0000000004          6            3      643.45
4       CUST0000000005         18            3      648.79
...                ...        ...          ...         ...
999995  CUST0000999996         14            4      423.98
999996  CUST0000999997          1            2      763.49
999997  CUST0000999998        139            3     1322.83
999998  CUST0000999999         17            2     1320.08
999999  CUST0001000000         85            2      198.31

[999812 rows x 4 columns]

In [136]:
RFM["R"] = pd.qcut(RFM["R_Recency"], 5, labels=[5, 4, 3, 2, 1])
RFM["F"] = pd.qcut(RFM["F_frequency"].rank(method="first"), 5, labels=[1, 2, 3, 4, 5])
RFM["M"] = pd.qcut(RFM["M_Monetary"].rank(method="first"), 5, labels=[1, 2, 3, 4, 5])
RFM

           customer_id  R_Recency  F_frequency  M_Monetary  R  F  M
0       CUST0000000001         16            1      144.39  4  1  1
1       CUST0000000002        134            2     1602.22  1  2  3
2       CUST0000000003         11            4      328.81  4  4  1
3       CUST0000000004          6            3      643.45  5  3  2
4       CUST0000000005         18            3      648.79  4  3  2
...                ...        ...          ...         ... .. .. ..
999995  CUST0000999996         14            4      423.98  4  5  2
999996  CUST0000999997          1            2      763.49  5  3  2
999997  CUST0000999998        139            3     1322.83  1  4  3
999998  CUST0000999999         17            2     1320.08  4  3  3
999999  CUST0001000000         85            2      198.31  1  3  1

[999812 rows x 7 columns]

In [137]:
RFM["RFM Score"] = (
    RFM["R"].astype(str) + 
    RFM["F"].astype(str) + 
    RFM["M"].astype(str)
).astype(int)

def segmentation(score):
    score = int(score)
    if score <= 155:
        return "Bronze"
    elif score <= 255:
        return "Silver"
    elif score <= 355:
        return "Gold"
    elif score <= 455:
        return "Platinium"
    else:
        return "Taitinium"

RFM["customer segmentation"] = RFM["RFM Score"].apply(segmentation)

RFM

,customer_id,R_Recency,F_frequency,M_Monetary,R,F,M,RFM Score,customer segmentation
0,CUST0000000001,16,1,144.39,4,1,1,411,Platinium
1,CUST0000000002,134,2,1602.22,1,2,3,123,Bronze
2,CUST0000000003,11,4,328.81,4,4,1,441,Platinium
3,CUST0000000004,6,3,643.45,5,3,2,532,Taitinium
4,CUST0000000005,18,3,648.79,4,3,2,432,Platinium
...,...,...,...,...,...,...,...,...,...
999995,CUST0000999996,14,4,423.98,4,5,2,452,Platinium
999996,CUST0000999997,1,2,763.49,5,3,2,532,Taitinium
999997,CUST0000999998,139,3,1322.83,1,4,3,143,Bronze
999998,CUST0000999999,17,2,1320.08,4,3,3,433,Platinium
999999,CUST0001000000,85,2,198.31,1,3,1,131,Bronze

In [138]:
segmentation_count = RFM["customer segmentation"].value_counts().reset_index()
segmentation_count.columns = ["Segment", "No. customers"]
segmentation_count

     Segment  No. customers
0  Taitinium         217581
1       Gold         206460
2     Bronze         196952
3     Silver         195814
4  Platinium         183005

In [139]:
churn

,customer_id,age,annual_income,dependents,tenure(months),contract,payment_method,monthlycharges,totalcharges,num_services,...,Age_Group,Service_Efficiency,Satisfaction_Category,Complaints_Calls_Gap,Calls_Per_Tenure_Month,Is_Long_Tenure,MonthlyCharges_Category,Avg_MonthlyCharges_By_Contract,Risk_Score,Risk_Level
0,CUST0000000001,43,55085.25,1,2,TWO YEAR,ELECTRONIC CHECK,67.20,144.39,1,...,Adult,0.500000,Excellent,0,0.000000,0,Medium,86.301024,0,Low Risk
1,CUST0000000002,18,60786.11,1,22,ONE YEAR,BANK TRANSFER,71.54,1602.22,2,...,Under 18,0.090909,Good,-3,0.136364,0,High,86.401616,30,Medium Risk
2,CUST0000000003,38,73184.32,0,3,TWO YEAR,CREDIT CARD,112.20,328.81,4,...,Adult,1.333333,Good,0,0.333333,0,High,86.301024,0,Low Risk
3,CUST0000000004,44,40923.78,1,6,TWO YEAR,BANK TRANSFER,107.49,643.45,3,...,Adult,0.500000,Average,0,0.333333,0,High,86.301024,30,Medium Risk
4,CUST0000000005,45,36400.94,0,9,TWO YEAR,CREDIT CARD,110.05,648.79,3,...,Adult,0.333333,Excellent,0,0.111111,0,High,86.301024,0,Low Risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,CUST0000999996,25,21309.78,4,5,ONE YEAR,CREDIT CARD,90.70,423.98,4,...,Young,0.800000,Poor,-1,0.400000,0,High,86.401616,25,Low Risk
999996,CUST0000999997,22,164236.89,1,11,ONE YEAR,ELECTRONIC CHECK,68.48,763.49,2,...,Young,0.181818,Average,-3,0.272727,0,Medium,86.401616,0,Low Risk
999997,CUST0000999998,44,34258.27,1,12,ONE YEAR,ELECTRONIC CHECK,101.98,1322.83,3,...,Adult,0.250000,Good,0,0.000000,0,High,86.401616,0,Low Risk
999998,CUST0000999999,65,38687.93,0,24,ONE YEAR,BANK TRANSFER,60.36,1320.08,2,...,Senior,0.083333,Average,0,0.000000,0,Medium,86.401616,0,Low Risk
999999,CUST0001000000,31,23617.51,1,3,ONE YEAR,MAILED CHECK,72.41,198.31,2,...,Adult,0.666667,Good,-1,0.333333,0,High,86.401616,30,Medium Risk

In [140]:
churn.to_csv("Final_Projecttt.csv")